services:
  - type: web
    name: ragify-ai-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: CHUNK_SIZE
        value: "600"
      - key: CHUNK_OVERLAP
        value: "100"
      - key: TOP_K
        value: "5"
    healthCheckPath: /health